services:
  - type: web
    name: hariom-groceries
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    publishDirectory: ./
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
